### ISSUE TITLE
Uncaught TypeError: Loupe\Loupe\Internal\Engine::loadNGramsFile(): Return value must be of type ?string, bool returned

### ISSUE THREAD

**Issue by soderlind** [loupe-php/loupe#64]
When adding a document array using `$loupe->addDocuments($documents)`, I get the following error:

```log
 PHP Fatal error:  Uncaught TypeError: Loupe\Loupe\Internal\Engine::loadNGramsFile(): Return value must be of type ?string, bool returned in /PATH/plugins/wp-loupe/vendor/loupe/loupe/src/Internal/Engine.php:340
Stack trace:
#0 /PATH/plugins/wp-loupe/vendor/loupe/loupe/src/Internal/Engine.php(165): Loupe\Loupe\Internal\Engine->loadNGramsFile(Array)
#1 /PATH/plugins/wp-loupe/vendor/loupe/loupe/src/Internal/Index/Indexer.php(351): Loupe\Loupe\Internal\Engine->getTokenizer()
#2 /PATH/plugins/wp-loupe/vendor/loupe/loupe/src/Internal/Index/Indexer.php(66): Loupe\Loupe\Internal\Index\Indexer->indexTerms(Array, 1)
#3 /PATH/plugins/wp-loupe/vendor/doctrine/dbal/src/Connection.php(1277): Loupe\Loupe\Internal\Index\Indexer->Loupe\Loupe\Internal\Index\{closure}(Object(Doctrine\DBAL\Connection))
#4 /PATH/plugins/wp-loupe/vendor/loupe/loupe/src/Internal/Index/Indexer.php(67): Doctrine\DBAL\Connection->transactional(Object(Closure))
#5 /PATH/plugins/wp-loupe/vendor/doctrine/dbal/src/Connection.php(1277): Loupe\Loupe\Internal\Index\Indexer->Loupe\Loupe\Internal\Index\{closure}(Object(Doctrine\DBAL\Connection))
#6 /PATH/plugins/wp-loupe/vendor/loupe/loupe/src/Internal/Index/Indexer.php(87): Doctrine\DBAL\Connection->transactional(Object(Closure))
#7 /PATH/plugins/wp-loupe/vendor/loupe/loupe/src/Internal/Engine.php(68): Loupe\Loupe\Internal\Index\Indexer->addDocuments(Array)
#8 /PATH/plugins/wp-loupe/vendor/loupe/loupe/src/Loupe.php(30): Loupe\Loupe\Internal\Engine->addDocuments(Array)
#9 /PATH/plugins/wp-loupe/includes/class-wploupe.php(329): Loupe\Loupe\Loupe->addDocuments(Array)
```

Here's a dump of the array (just the last element, I tried to use `addDocument()`and one item at the time, it also failed on the same element):

```
Array(
   [42] => Array
        (
            [id] => 238
            [title] => Pariatur voluptate alias quis numquam dignissimos
            [content] => Laudantium et aspernatur fugiat. Nihil omnis cum illo et molestiae. Natus non voluptates molestias dolor. Distinctio iste et. Odio aut dicta aut. Ipsam blanditiis praesentium ipsam recusandae illo. dolor mollitia dolorem vero Impedit deserunt minima explicabo ipsam. Qui suscipit illum amet sit necessitatibus Explicabo doloremque adipisci culpa ad molestiae. quis porro blanditiis Qui qui perferendis similique Tempora optio quaerat consectetur id accusamus. Vitae libero accusamus repellendus Soluta non deserunt voluptas sint doloremque. Dignissimos animi cumque Et sint temporibus asperiores eum. a corporis reiciendis excepturi esse explicabo. Sed facilis et voluptatem. Maxime ducimus voluptatem perspiciatis at ex. Optio facilis aut voluptatem quia. corrupti excepturi inventore. Sit animi excepturi dolores consequatur et deleniti. voluptates sint est expedita ut possimus. eos perferendis veritatis nulla magnam. Aut ut quia maxime neque doloremque sit Inventore a et sit. Est dolorem praesentium.

Repudiandae odit quo quae laboriosam reprehenderit hic. Dolores veniam saepe deserunt quas. Sed quis minima sed aut. Placeat vitae nobis dolorem exercitationem
Excepturi asperiores delectus sunt non. Voluptate et commodi nesciunt. recusandae et tenetur. Illo quos aut Occaecati sit veniam laudantium modi eum. Tempora quas assumenda. Quaerat commodi velit perspiciatis dolorem similique adipisci. Doloremque quo est a molestiae ut. Distinctio autem aut temporibus rerum. Dolorem aut sint aperiam laborum. Rem est placeat aspernatur. Praesentium quas suscipit. Eum sit enim et. Aliquid explicabo quia voluptatem Debitis aut adipisci aut. aut totam iste dolorem. reprehenderit excepturi hic totam quia. Id quas iste consequuntur nihil aliquid Ex delectus consequuntur non est nisi harum. Quia explicabo sit est. Error magni adipisci voluptas perferendis. Ut esse molestias qui eaque nulla velit voluptatem. Sit ut unde. Molestias quaerat eaque eveniet voluptatum excepturi. quisquam quisquam saepe doloremque

Qui omnis asperiores aut cupiditate quas inventore
Sit velit aliquam sedImpeditOfficia fugit quis utIste voluptatem ducimus qui modi quaerat veniam utNesciunt quos est ut sit
Est ut eum architecto. Adipisci similique doloribus pariatur voluptatum sunt ea. Ad unde quas itaque eaque tenetur nobis. Voluptates omnis at dolor unde illo assumenda
Consequuntur fuga dolor sit Laudantium hic praesentium repellat et harum. Quae perferendis rerum in ut Rerum aut voluptatibus iusto veritatis. Rerum ipsa architecto quisquam aut. Est et reiciendis praesentium id. A quia aut dolorem id unde. Repellendus deserunt voluptates odio qui Corrupti sequi omnis quos ullam. Similique qui cumque ratione commodi omnis tempora Voluptate ratione velit id nam nihil deserunt
Odio nihil quia maxime ipsam laboriosam. Molestiae commodi doloremque voluptatum vitae quibusdam error
Facilis qui non odio in perferendisAut et minima deleniti nihil velitNobis qui neque esseNostrum vero beatae mollitia unde veritatis deserunt optioVoluptas aliquid eius aut accusamus ut quosVeniam eiusIusto dolore officiis molestiae sapiente et eius
Quasi et aut dolore rerumNisi nobis undeAut consequatur et est laudantiumEt facilis quia non esseReiciendis fugiatEst enim ipsa rationeVelit et ducimus quia ea eligendi
            [url] => http://plugins.local/loupe/2024/01/03/pariatur-voluptate-alias-quis-numquam-dignissimos/
            [date] => 1704307585
        )
)
```

I created the index using the following code:

```php
	/**
	 * Create a new Loupe instance for each post type.
	 *
	 * @return void
	 */
	public function init(): void {
		$iso6391_lang = ( '' === \get_locale() ) ? 'en' : strtolower( substr( \get_locale(), 0, 2 ) );
		foreach ( $this->post_types as $post_type ) {

			$filterable_attributes = \apply_filters( "wp_loupe_filterable_attribute_{$post_type}", [ 'title', 'content' ] );

			$configuration = Configuration::create()
				->withPrimaryKey( 'id' )
				->withFilterableAttributes( $filterable_attributes )
				->withSortableAttributes( [ 'date','title' ] )
				->withLanguages( [ $iso6391_lang ] )
				->withTypoTolerance( TypoTolerance::create()->withFirstCharTypoCountsDouble( false ) );

			$db_path                   = apply_filters( 'wp_loupe_db_path', WP_CONTENT_DIR . '/wp-loupe-db' );
			$db_path                   = "{$db_path}/{$post_type}";
			$loupe_factory             = new LoupeFactory();
			$this->loupe[ $post_type ] = $loupe_factory->create( $db_path, $configuration );
		}
	}
```

**Comment by soderlind** [comment]
So .. removed `->withLanguages( [ $iso6391_lang ] )` and indexing works.

**Comment by soderlind** [comment]
on test, $iso6391_lang is `en`

**Comment by soderlind** [comment]
.. my idea was that it's better to set the language than autodetect.

**Comment by Toflar** [comment]
Can you provide a standalone reproducer? Something along the lines of the example in the README? https://github.com/loupe-php/loupe#usage

**Comment by soderlind** [comment]
I believe the problem lays in my code, will reopen if not.
